dataset: CelebA_HQ
classifier: 
  model: FaceNet
  lr: 0.001
  momentum: 0.9
  num_epochs: 60
  num_workers : 4
  batch_size: 16


paths:
  gender_dataset: dataset/CelebA_HQ_face_gender_dataset
  identity_dataset: dataset/CelebA_HQ_facial_identity_dataset
  detail_code: /home/leewlving/PycharmProjects/BDInvert_Release/BDInvert/work_dirs/inversion/stylegan2_ffhq1024/invert_detailcode
  base_code: /home/leewlving/PycharmProjects/BDInvert_Release/BDInvert/work_dirs/inversion/stylegan2_ffhq1024/invert_basecode
  inverter_cfg: /dataset/face_identity/psp_ffhq_encode.pt
  classifier: checkpoint
  stylegan: checkpoint/stylegan2-ffhq-config-f.pt
  stylegan2: checkpoint/stylegan2_ffhq1024.pth
  adv_embedding: pretrained_models
  pretrained_models : pretrained_models

prompt: a face with red lipstick
resolution: 1024
basecode_spatial_size: 16

# available attributes
# ['Blond_Hair', 'Wavy_Hair', 'Young', 'Eyeglasses', 'Heavy_Makeup', 'Rosy_Cheeks',
#                               'Chubby', 'Mouth_Slightly_Open', 'Bushy_Eyebrows', 'Wearing_Lipstick', 'Smiling',
#                               'Arched_Eyebrows', 'Bangs', 'Wearing_Earrings', 'Bags_Under_Eyes', 'Receding_Hairline', 'Pale_Skin']

optim:
  batch_size: 4
  num_epochs: 10
  num_workers : 4
  images_resize: 256
  epsilon: 0.05
  noise_epsilon: 0.1
  delta: 100
  beta: 1